"""
Risk Limits & Circuit Breakers.

This module protects your capital with automatic safety mechanisms:

1. Daily Loss Limit - Stop trading if you lose X% in a day
2. Drawdown Circuit Breaker - Reduce exposure when drawdown exceeds threshold
3. Consecutive Loss Limit - Pause after N losing trades in a row
4. Position Time Limit - Auto-exit positions held too long

WHY THIS MATTERS:
The #1 cause of blowing up accounts is not having risk limits.
When you're on a losing streak, emotions take over.
This module removes emotion and enforces discipline.

MILLIONAIRE MINDSET:
- Small losses are OK. Large losses kill accounts.
- Live to trade another day.
- Protecting capital is MORE important than making money.
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Callable
from datetime import date, datetime, timedelta
from enum import Enum
from loguru import logger

from core.config import settings


class RiskState(Enum):
    """Current risk state of the trading system."""
    NORMAL = "normal"                   # Normal trading
    CAUTION = "caution"                 # Reduced position sizes
    DANGER = "danger"                   # Minimum positions only
    HALTED = "halted"                   # Trading halted


@dataclass
class RiskAlert:
    """Alert generated by risk monitoring."""
    timestamp: datetime
    level: str                          # INFO, WARNING, DANGER
    category: str                       # drawdown, daily_loss, etc.
    message: str
    value: float                        # The metric value that triggered
    threshold: float                    # The threshold that was exceeded
    action: str                         # Recommended action


@dataclass
class DailyStats:
    """Trading statistics for a single day."""
    date: date
    starting_value: float
    ending_value: float
    high_value: float
    low_value: float
    trades: int
    wins: int
    losses: int
    realized_pnl: float
    unrealized_pnl: float
    
    @property
    def daily_return_pct(self) -> float:
        if self.starting_value == 0:
            return 0
        return (self.ending_value - self.starting_value) / self.starting_value * 100
    
    @property
    def win_rate(self) -> float:
        if self.trades == 0:
            return 0
        return self.wins / self.trades * 100
    
    @property
    def intraday_drawdown_pct(self) -> float:
        if self.high_value == 0:
            return 0
        return (self.high_value - self.low_value) / self.high_value * 100


@dataclass
class RiskLimits:
    """
    Risk limit configuration.
    
    These are the guardrails that keep you safe.
    Adjust based on your risk tolerance and experience.
    """
    
    # Daily limits
    max_daily_loss_pct: float = 3.0         # Stop trading if down 3% today
    max_daily_trades: int = 10              # Max trades per day
    
    # Drawdown limits
    drawdown_caution_pct: float = 10.0      # Enter caution mode at 10% DD
    drawdown_danger_pct: float = 15.0       # Enter danger mode at 15% DD
    drawdown_halt_pct: float = 20.0         # Halt trading at 20% DD
    
    # Consecutive loss limits
    max_consecutive_losses: int = 5         # Pause after 5 losses in a row
    
    # Position time limits (for swing trading)
    max_holding_days: int = 30              # Auto-review positions held > 30 days
    
    # Exposure limits (during different risk states)
    normal_max_exposure: float = 0.80       # 80% invested in normal state
    caution_max_exposure: float = 0.50      # 50% invested in caution state
    danger_max_exposure: float = 0.25       # 25% invested in danger state
    
    # Position size multipliers
    normal_position_mult: float = 1.0       # Full position size
    caution_position_mult: float = 0.5      # Half position size
    danger_position_mult: float = 0.25      # Quarter position size


class RiskManager:
    """
    Monitors and enforces risk limits.
    
    Usage:
        risk_mgr = RiskManager(
            initial_capital=500_000,
            limits=RiskLimits(max_daily_loss_pct=3.0)
        )
        
        # Check before trading
        if risk_mgr.can_trade():
            # Execute trade
            risk_mgr.record_trade(won=True, pnl=5000)
        else:
            print(f"Trading halted: {risk_mgr.halt_reason}")
        
        # Daily monitoring
        risk_mgr.update(current_portfolio_value=520_000)
        
        # Get current state
        state = risk_mgr.get_risk_state()
        position_mult = risk_mgr.get_position_size_multiplier()
    """
    
    def __init__(
        self,
        initial_capital: float,
        limits: RiskLimits = None,
        alert_callback: Optional[Callable] = None,
    ):
        self.initial_capital = initial_capital
        self.limits = limits or RiskLimits()
        self.alert_callback = alert_callback
        
        # Current state
        self.current_value = initial_capital
        self.peak_value = initial_capital
        self.current_state = RiskState.NORMAL
        self.halt_reason = ""
        
        # Daily tracking
        self.today_start_value = initial_capital
        self.today_high_value = initial_capital
        self.today_low_value = initial_capital
        self.today_trades = 0
        self.today_wins = 0
        self.today_losses = 0
        self.today_pnl = 0.0
        
        # Consecutive tracking
        self.consecutive_losses = 0
        self.consecutive_wins = 0
        
        # History
        self.daily_stats: List[DailyStats] = []
        self.alerts: List[RiskAlert] = []
        
        logger.info(
            f"RiskManager initialized: Capital={initial_capital:,.0f}, "
            f"MaxDailyLoss={self.limits.max_daily_loss_pct}%, "
            f"MaxDrawdown={self.limits.drawdown_halt_pct}%"
        )
    
    @property
    def drawdown_pct(self) -> float:
        """Current drawdown from peak."""
        if self.peak_value == 0:
            return 0
        return (self.peak_value - self.current_value) / self.peak_value * 100
    
    @property
    def daily_pnl_pct(self) -> float:
        """Today's P&L percentage."""
        if self.today_start_value == 0:
            return 0
        return (self.current_value - self.today_start_value) / self.today_start_value * 100
    
    @property
    def total_return_pct(self) -> float:
        """Total return from initial capital."""
        return (self.current_value - self.initial_capital) / self.initial_capital * 100
    
    def update(self, current_portfolio_value: float):
        """
        Update with current portfolio value.
        
        Call this regularly (at least at market open/close).
        """
        self.current_value = current_portfolio_value
        
        # Update peak
        if current_portfolio_value > self.peak_value:
            self.peak_value = current_portfolio_value
        
        # Update daily highs/lows
        self.today_high_value = max(self.today_high_value, current_portfolio_value)
        self.today_low_value = min(self.today_low_value, current_portfolio_value)
        
        # Check risk conditions
        self._check_all_limits()
    
    def _check_all_limits(self):
        """Check all risk limits and update state."""
        # Check daily loss
        if self.daily_pnl_pct <= -self.limits.max_daily_loss_pct:
            self._halt_trading(
                f"Daily loss limit exceeded: {self.daily_pnl_pct:.2f}%"
            )
            self._create_alert(
                "DANGER",
                "daily_loss",
                f"Daily loss limit hit: {self.daily_pnl_pct:.2f}%",
                abs(self.daily_pnl_pct),
                self.limits.max_daily_loss_pct,
                "HALT TRADING FOR TODAY"
            )
            return
        
        # Check drawdown
        dd = self.drawdown_pct
        
        if dd >= self.limits.drawdown_halt_pct:
            self._halt_trading(
                f"Maximum drawdown exceeded: {dd:.2f}%"
            )
            self._create_alert(
                "DANGER",
                "drawdown",
                f"Max drawdown limit hit: {dd:.2f}%",
                dd,
                self.limits.drawdown_halt_pct,
                "HALT ALL TRADING - REVIEW STRATEGY"
            )
        elif dd >= self.limits.drawdown_danger_pct:
            self.current_state = RiskState.DANGER
            self._create_alert(
                "WARNING",
                "drawdown",
                f"Danger zone drawdown: {dd:.2f}%",
                dd,
                self.limits.drawdown_danger_pct,
                "REDUCE POSITIONS TO 25% EXPOSURE"
            )
        elif dd >= self.limits.drawdown_caution_pct:
            self.current_state = RiskState.CAUTION
            self._create_alert(
                "INFO",
                "drawdown",
                f"Caution zone drawdown: {dd:.2f}%",
                dd,
                self.limits.drawdown_caution_pct,
                "REDUCE POSITION SIZES BY 50%"
            )
        else:
            # Only reset to NORMAL if we're not halted
            if self.current_state != RiskState.HALTED:
                self.current_state = RiskState.NORMAL
        
        # Check consecutive losses
        if self.consecutive_losses >= self.limits.max_consecutive_losses:
            self._create_alert(
                "WARNING",
                "consecutive_loss",
                f"Hit {self.consecutive_losses} consecutive losses",
                self.consecutive_losses,
                self.limits.max_consecutive_losses,
                "TAKE A BREAK - REVIEW STRATEGY"
            )
    
    def _halt_trading(self, reason: str):
        """Halt trading."""
        self.current_state = RiskState.HALTED
        self.halt_reason = reason
        logger.warning(f"🚨 TRADING HALTED: {reason}")
    
    def _create_alert(
        self,
        level: str,
        category: str,
        message: str,
        value: float,
        threshold: float,
        action: str,
    ):
        """Create and store a risk alert."""
        alert = RiskAlert(
            timestamp=datetime.now(),
            level=level,
            category=category,
            message=message,
            value=value,
            threshold=threshold,
            action=action,
        )
        
        # Only add if not duplicate of recent alert
        if not self.alerts or self.alerts[-1].category != category:
            self.alerts.append(alert)
            
            # Call callback if set
            if self.alert_callback:
                self.alert_callback(alert)
            
            # Log based on level
            if level == "DANGER":
                logger.error(f"🚨 {message} - {action}")
            elif level == "WARNING":
                logger.warning(f"⚠️ {message} - {action}")
            else:
                logger.info(f"ℹ️ {message}")
    
    def can_trade(self) -> bool:
        """Check if trading is allowed."""
        if self.current_state == RiskState.HALTED:
            return False
        
        if self.today_trades >= self.limits.max_daily_trades:
            logger.warning(f"Max daily trades reached: {self.today_trades}")
            return False
        
        return True
    
    def record_trade(self, won: bool, pnl: float):
        """
        Record a completed trade.
        
        Args:
            won: True if trade was profitable
            pnl: Profit/loss amount
        """
        self.today_trades += 1
        self.today_pnl += pnl
        
        if won:
            self.today_wins += 1
            self.consecutive_wins += 1
            self.consecutive_losses = 0
        else:
            self.today_losses += 1
            self.consecutive_losses += 1
            self.consecutive_wins = 0
        
        logger.debug(
            f"Trade recorded: {'WIN' if won else 'LOSS'} Rs.{pnl:+,.2f} "
            f"(Consecutive: W{self.consecutive_wins}/L{self.consecutive_losses})"
        )
    
    def get_risk_state(self) -> RiskState:
        """Get current risk state."""
        return self.current_state
    
    def get_position_size_multiplier(self) -> float:
        """
        Get position size multiplier based on risk state.
        
        Use this to scale down positions during drawdowns.
        """
        if self.current_state == RiskState.HALTED:
            return 0.0
        elif self.current_state == RiskState.DANGER:
            return self.limits.danger_position_mult
        elif self.current_state == RiskState.CAUTION:
            return self.limits.caution_position_mult
        else:
            return self.limits.normal_position_mult
    
    def get_max_exposure(self) -> float:
        """Get maximum portfolio exposure based on risk state."""
        if self.current_state == RiskState.HALTED:
            return 0.0
        elif self.current_state == RiskState.DANGER:
            return self.limits.danger_max_exposure
        elif self.current_state == RiskState.CAUTION:
            return self.limits.caution_max_exposure
        else:
            return self.limits.normal_max_exposure
    
    def reset_daily(self):
        """
        Reset daily tracking (call at start of each trading day).
        """
        # Save yesterday's stats
        if self.today_trades > 0:
            stats = DailyStats(
                date=date.today() - timedelta(days=1),
                starting_value=self.today_start_value,
                ending_value=self.current_value,
                high_value=self.today_high_value,
                low_value=self.today_low_value,
                trades=self.today_trades,
                wins=self.today_wins,
                losses=self.today_losses,
                realized_pnl=self.today_pnl,
                unrealized_pnl=0,
            )
            self.daily_stats.append(stats)
        
        # Reset daily counters
        self.today_start_value = self.current_value
        self.today_high_value = self.current_value
        self.today_low_value = self.current_value
        self.today_trades = 0
        self.today_wins = 0
        self.today_losses = 0
        self.today_pnl = 0.0
        
        # Reset halt if it was due to daily loss (but not drawdown)
        if self.current_state == RiskState.HALTED and "Daily loss" in self.halt_reason:
            self.current_state = RiskState.NORMAL
            self.halt_reason = ""
            logger.info("Daily loss halt reset for new trading day")
    
    def resume_trading(self, reason: str = "Manual override"):
        """
        Resume trading after halt.
        
        Only use this after reviewing your strategy!
        """
        if self.current_state == RiskState.HALTED:
            self.current_state = RiskState.CAUTION  # Resume in caution mode
            logger.warning(f"Trading resumed: {reason}")
            self._create_alert(
                "INFO",
                "resume",
                f"Trading resumed: {reason}",
                0,
                0,
                "PROCEED WITH CAUTION"
            )
    
    def get_status_report(self) -> str:
        """Generate risk status report."""
        state_emoji = {
            RiskState.NORMAL: "🟢",
            RiskState.CAUTION: "🟡",
            RiskState.DANGER: "🟠",
            RiskState.HALTED: "🔴",
        }
        
        report = f"""
╔══════════════════════════════════════════════════════════════╗
║                     RISK STATUS REPORT                       ║
╠══════════════════════════════════════════════════════════════╣
║ State: {state_emoji[self.current_state]} {self.current_state.value.upper():10}                           ║
║                                                              ║
║ PORTFOLIO:                                                   ║
║   Current Value:  Rs. {self.current_value:>15,.2f}            ║
║   Peak Value:     Rs. {self.peak_value:>15,.2f}            ║
║   Drawdown:            {self.drawdown_pct:>10.2f}%                 ║
║   Total Return:        {self.total_return_pct:>+10.2f}%                 ║
║                                                              ║
║ TODAY:                                                       ║
║   Daily P&L:      Rs. {self.current_value - self.today_start_value:>+15,.2f}            ║
║   Daily Return:        {self.daily_pnl_pct:>+10.2f}%                 ║
║   Trades:              {self.today_trades:>5} / {self.limits.max_daily_trades}                  ║
║   Win/Loss:            {self.today_wins:>3} / {self.today_losses:<3}                     ║
║                                                              ║
║ LIMITS:                                                      ║
║   Max Daily Loss:      {self.limits.max_daily_loss_pct:>10.1f}%                 ║
║   Max Drawdown:        {self.limits.drawdown_halt_pct:>10.1f}%                 ║
║   Consecutive Losses:  {self.consecutive_losses:>5} / {self.limits.max_consecutive_losses}                  ║
║                                                              ║
║ CURRENT MULTIPLIERS:                                         ║
║   Position Size:       {self.get_position_size_multiplier():>10.0%}                 ║
║   Max Exposure:        {self.get_max_exposure():>10.0%}                 ║
╚══════════════════════════════════════════════════════════════╝
"""
        
        if self.current_state == RiskState.HALTED:
            report += f"\n🚨 HALT REASON: {self.halt_reason}\n"
        
        return report
    
    def get_recent_alerts(self, count: int = 5) -> List[RiskAlert]:
        """Get recent alerts."""
        return self.alerts[-count:]


# Convenience function for quick risk check
def check_risk(
    current_value: float,
    peak_value: float,
    today_start: float,
    max_daily_loss: float = 3.0,
    max_drawdown: float = 20.0,
) -> Tuple[bool, str]:
    """
    Quick risk check without full RiskManager.
    
    Returns:
        Tuple of (can_trade, warning_message)
    """
    # Daily loss check
    daily_pnl = (current_value - today_start) / today_start * 100
    if daily_pnl <= -max_daily_loss:
        return False, f"Daily loss limit exceeded: {daily_pnl:.2f}%"
    
    # Drawdown check
    drawdown = (peak_value - current_value) / peak_value * 100
    if drawdown >= max_drawdown:
        return False, f"Max drawdown exceeded: {drawdown:.2f}%"
    
    return True, "OK"


# Type hint
from typing import Tuple
