"""
Database configuration and models using SQLAlchemy 2.0.
Supports SQLite for development and PostgreSQL for production.
"""

from datetime import datetime, date, timezone
from typing import Optional, List
from decimal import Decimal

from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    String,
    Float,
    DateTime,
    Date,
    Boolean,
    Text,
    ForeignKey,
    Index,
    UniqueConstraint,
    event,
)
from sqlalchemy.orm import (
    declarative_base,
    sessionmaker,
    relationship,
    Session,
)
from sqlalchemy.pool import NullPool, QueuePool

from core.config import settings
from loguru import logger

# Create declarative base
Base = declarative_base()


# ============ DATABASE MODELS ============

class Stock(Base):
    """
    Master list of NEPSE stocks.
    Updated periodically from NEPSE API.
    """
    __tablename__ = "stocks"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=True)
    sector = Column(String(100), nullable=True)  # Banking, Hydropower, Insurance, etc.
    
    # Metadata
    listed_shares = Column(Float, nullable=True)
    market_cap = Column(Float, nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True)
    last_updated = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    
    # Relationships
    prices = relationship("DailyPrice", back_populates="stock", lazy="dynamic")
    signals = relationship("Signal", back_populates="stock", lazy="dynamic")
    
    def __repr__(self):
        return f"<Stock {self.symbol}>"


class DailyPrice(Base):
    """
    Daily OHLCV data for each stock.
    This is the foundation for all technical analysis.
    """
    __tablename__ = "daily_prices"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False)
    date = Column(Date, nullable=False, index=True)
    
    # OHLCV - Core price data
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)  # Number of shares traded
    
    # Additional NEPSE-specific data
    turnover = Column(Float, nullable=True)  # Rs. value traded
    trades = Column(Integer, nullable=True)  # Number of transactions
    
    # Pre-calculated indicators (for faster queries)
    ema_9 = Column(Float, nullable=True)
    ema_21 = Column(Float, nullable=True)
    rsi_14 = Column(Float, nullable=True)
    volume_avg_20 = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    # Relationships
    stock = relationship("Stock", back_populates="prices")
    
    # Unique constraint: one record per stock per day
    __table_args__ = (
        UniqueConstraint("stock_id", "date", name="unique_stock_date"),
        Index("idx_stock_date", "stock_id", "date"),
    )
    
    def __repr__(self):
        return f"<DailyPrice {self.stock_id} @ {self.date}: {self.close}>"


class Signal(Base):
    """
    Trading signals generated by the screener.
    Stores both raw signals and AI analysis results.
    """
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False)
    date = Column(Date, nullable=False, index=True)
    
    # Signal type and strength
    signal_type = Column(String(50), nullable=False)  # BUY, SELL, HOLD
    strategy_name = Column(String(100), nullable=False)  # golden_cross, rsi_divergence, etc.
    confidence_score = Column(Float, nullable=True)  # 1-10 score
    
    # Technical data at signal time
    entry_price = Column(Float, nullable=False)
    target_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    
    # Indicator values at signal time
    rsi = Column(Float, nullable=True)
    ema_9 = Column(Float, nullable=True)
    ema_21 = Column(Float, nullable=True)
    volume_spike = Column(Float, nullable=True)  # Multiple of average volume
    
    # AI Analysis
    ai_verdict = Column(String(50), nullable=True)  # STRONG_BUY, BUY, RISKY, AVOID
    ai_analysis = Column(Text, nullable=True)  # Full AI response
    news_summary = Column(Text, nullable=True)  # Scraped news context
    
    # Outcome tracking (filled later)
    outcome = Column(String(50), nullable=True)  # WIN, LOSS, PENDING
    actual_exit_price = Column(Float, nullable=True)
    profit_loss_pct = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    # Relationships
    stock = relationship("Stock", back_populates="signals")
    
    __table_args__ = (
        Index("idx_signal_date_type", "date", "signal_type"),
    )
    
    def __repr__(self):
        return f"<Signal {self.signal_type} {self.stock_id} @ {self.date}>"


class Trade(Base):
    """
    Actual trades executed (or paper trades for tracking).
    Links to signals and tracks performance.
    """
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey("signals.id"), nullable=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False)
    
    # Trade details
    trade_type = Column(String(10), nullable=False)  # BUY, SELL
    entry_date = Column(Date, nullable=False)
    entry_price = Column(Float, nullable=False)
    quantity = Column(Integer, nullable=False)
    
    # Exit details (filled when closed)
    exit_date = Column(Date, nullable=True)
    exit_price = Column(Float, nullable=True)
    
    # Calculated fields
    position_size = Column(Float, nullable=True)  # Rs. invested
    profit_loss = Column(Float, nullable=True)  # Rs. gained/lost
    profit_loss_pct = Column(Float, nullable=True)
    
    # Status
    status = Column(String(20), default="OPEN")  # OPEN, CLOSED, CANCELLED
    is_paper_trade = Column(Boolean, default=True)
    
    # Risk management
    stop_loss_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))
    
    def __repr__(self):
        return f"<Trade {self.trade_type} {self.stock_id} @ {self.entry_date}>"


class MarketData(Base):
    """
    Overall NEPSE market data (indices, breadth).
    Used for market regime detection.
    """
    __tablename__ = "market_data"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, unique=True, nullable=False, index=True)
    
    # NEPSE Index
    nepse_index = Column(Float, nullable=True)
    nepse_change = Column(Float, nullable=True)
    nepse_change_pct = Column(Float, nullable=True)
    
    # Market breadth
    advances = Column(Integer, nullable=True)  # Stocks that went up
    declines = Column(Integer, nullable=True)  # Stocks that went down
    unchanged = Column(Integer, nullable=True)
    
    # Market turnover
    total_turnover = Column(Float, nullable=True)
    total_volume = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=True)
    
    # Sector indices (top sectors)
    banking_index = Column(Float, nullable=True)
    hydropower_index = Column(Float, nullable=True)
    insurance_index = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    def __repr__(self):
        return f"<MarketData {self.date}: NEPSE {self.nepse_index}>"


class BacktestResult(Base):
    """
    Stores backtesting results for strategy validation.
    """
    __tablename__ = "backtest_results"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(100), nullable=False)
    
    # Test period
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    
    # Parameters used
    parameters = Column(Text, nullable=True)  # JSON string
    
    # Results
    total_trades = Column(Integer, nullable=True)
    winning_trades = Column(Integer, nullable=True)
    losing_trades = Column(Integer, nullable=True)
    win_rate = Column(Float, nullable=True)
    
    # Returns
    total_return_pct = Column(Float, nullable=True)
    cagr = Column(Float, nullable=True)
    
    # Risk metrics
    sharpe_ratio = Column(Float, nullable=True)
    sortino_ratio = Column(Float, nullable=True)
    max_drawdown = Column(Float, nullable=True)
    
    # Additional
    profit_factor = Column(Float, nullable=True)
    expectancy = Column(Float, nullable=True)
    
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    
    def __repr__(self):
        return f"<BacktestResult {self.strategy_name}: {self.total_return_pct}%>"


class LivePosition(Base):
    """
    Persistent live/paper positions — survives process restarts.
    Phase 4.6: position persistence to SQLite.
    """
    __tablename__ = "live_positions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, index=True)
    shares = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    entry_date = Column(Date, nullable=False)
    sector = Column(String(100), default="")

    # Stops
    stop_loss = Column(Float, default=0.0)
    trailing_stop = Column(Float, default=0.0)
    target_price = Column(Float, default=0.0)
    highest_price = Column(Float, default=0.0)  # for trailing
    current_atr = Column(Float, default=0.0)

    # State
    status = Column(String(20), default="OPEN")  # OPEN, CLOSED
    css_score = Column(Float, default=0.0)

    # Exit
    exit_price = Column(Float, nullable=True)
    exit_date = Column(Date, nullable=True)
    exit_reason = Column(String(50), default="")

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f"<LivePosition {self.symbol} {self.shares}@{self.entry_price} [{self.status}]>"


class DailyBreadth(Base):
    """
    Daily market breadth history — Phase 5.6.
    Stores daily A/D data for divergence detection over time.
    """
    __tablename__ = "daily_breadth"
    __table_args__ = (
        UniqueConstraint("date", name="uq_daily_breadth_date"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, index=True)
    total_stocks = Column(Integer, default=0)
    advancing = Column(Integer, default=0)
    declining = Column(Integer, default=0)
    unchanged = Column(Integer, default=0)
    breadth_pct = Column(Float, default=0.0)
    ad_ratio = Column(Float, default=0.0)
    nepse_index = Column(Float, default=0.0)
    nepse_change_pct = Column(Float, default=0.0)
    regime = Column(String(20), default="NEUTRAL")

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f"<DailyBreadth {self.date}: {self.advancing}A/{self.declining}D>"


class MacroSnapshot(Base):
    """
    NRB macroeconomic data snapshots — Phase 5.4.
    Manual-entry + scoring framework for key indicators.
    """
    __tablename__ = "macro_snapshots"
    __table_args__ = (
        UniqueConstraint("date", name="uq_macro_date"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(Date, nullable=False, index=True)

    # NRB indicators
    interbank_rate = Column(Float, nullable=True)      # Daily NRB rate
    ccd_ratio = Column(Float, nullable=True)            # Credit-to-Core-Deposit
    inflation_rate = Column(Float, nullable=True)       # YoY CPI inflation
    remittance_growth = Column(Float, nullable=True)    # Monthly remittance growth %
    base_rate = Column(Float, nullable=True)            # NRB base rate

    # Derived scores (0-100)
    liquidity_score = Column(Float, default=50.0)
    banking_health_score = Column(Float, default=50.0)
    overall_macro_score = Column(Float, default=50.0)

    notes = Column(Text, default="")

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f"<MacroSnapshot {self.date}: macro={self.overall_macro_score:.0f}>"


# ============ DATABASE ENGINE & SESSION ============

def get_engine():
    """Create database engine based on configuration."""
    if settings.database_is_sqlite:
        # SQLite: use NullPool (new connection per request) with WAL mode
        # WAL mode allows concurrent reads while writing
        engine = create_engine(
            settings.database_url,
            connect_args={"check_same_thread": False},
            poolclass=NullPool,
            echo=False,
        )
    else:
        # PostgreSQL or other databases
        engine = create_engine(
            settings.database_url,
            pool_pre_ping=True,
            pool_size=5,
            max_overflow=10,
            poolclass=QueuePool,
            echo=False,
        )
    return engine


# Create engine and session factory
engine = get_engine()
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def init_db():
    """
    Initialize database tables.
    Call this on application startup.
    """
    logger.info("Initializing database...")
    Base.metadata.create_all(bind=engine)
    logger.info("Database initialized successfully.")


def get_db() -> Session:
    """
    Dependency function to get database session.
    Use with FastAPI Depends or as context manager.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# Enable foreign keys and WAL mode for SQLite
@event.listens_for(engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    """Enable foreign key support and WAL mode for SQLite."""
    if settings.database_is_sqlite:
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.execute("PRAGMA journal_mode=WAL")
        cursor.execute("PRAGMA busy_timeout=5000")
        cursor.close()
