"""
Base Strategy class for trading strategies.
All strategies inherit from this abstract class.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date
from typing import Optional, List, Dict, Any, Tuple
import pandas as pd
from loguru import logger


@dataclass
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.
    """
    symbol: str
    date: date
    signal_type: str  # BUY, SELL, HOLD
    confidence: float  # 1-10 score
    entry_price: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    strategy_name: str = ""
    reason: str = ""  # Human-readable explanation
    indicators: Dict[str, Any] = None  # Indicator values at signal time
    
    def __post_init__(self):
        if self.indicators is None:
            self.indicators = {}
        
        # Calculate target and stop loss if not provided
        if self.target_price is None and self.signal_type == "BUY":
            self.target_price = self.entry_price * 1.10  # 10% target
        
        if self.stop_loss is None and self.signal_type == "BUY":
            self.stop_loss = self.entry_price * 0.95  # 5% stop loss


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Each strategy must implement:
    - name: Strategy identifier
    - analyze(): Main analysis method that returns signals
    """
    
    def __init__(self, params: Dict[str, Any] = None):
        """
        Initialize strategy with optional parameters.
        
        Args:
            params: Strategy-specific parameters for optimization
        """
        self.params = params or {}
        self._setup_params()
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Unique name for this strategy."""
        pass
    
    @property
    def description(self) -> str:
        """Human-readable description of the strategy."""
        return f"Trading strategy: {self.name}"
    
    def _setup_params(self):
        """
        Set up default parameters. Override in subclasses.
        """
        pass
    
    @abstractmethod
    def analyze(self, df: pd.DataFrame, symbol: str) -> Optional[StrategySignal]:
        """
        Analyze price data and generate signal if conditions are met.
        
        Args:
            df: DataFrame with OHLCV data and indicators
            symbol: Stock symbol
            
        Returns:
            StrategySignal if conditions met, None otherwise
        """
        pass
    
    def validate_data(self, df: pd.DataFrame, min_rows: int = 30) -> bool:
        """
        Validate that we have enough data for analysis.
        
        Args:
            df: DataFrame to validate
            min_rows: Minimum required rows
            
        Returns:
            True if valid, False otherwise
        """
        if df is None or df.empty:
            logger.warning(f"{self.name}: Empty DataFrame")
            return False
        
        if len(df) < min_rows:
            logger.warning(f"{self.name}: Insufficient data ({len(df)} < {min_rows})")
            return False
        
        return True
    
    def get_latest_values(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Get the latest row values as a dictionary.
        
        Args:
            df: DataFrame with indicators
            
        Returns:
            Dict of latest values
        """
        if df.empty:
            return {}
        return df.iloc[-1].to_dict()
    
    def calculate_confidence(self, factors: List[Tuple[str, bool, float]]) -> float:
        """
        Calculate confidence score based on multiple factors.
        
        Args:
            factors: List of (name, condition_met, weight) tuples
            
        Returns:
            Confidence score from 1-10
        """
        total_weight = sum(f[2] for f in factors)
        met_weight = sum(f[2] for f in factors if f[1])
        
        if total_weight == 0:
            return 5.0
        
        # Scale to 1-10
        raw_score = (met_weight / total_weight) * 10
        return max(1.0, min(10.0, raw_score))


# Type alias for strategy signal with type hint
from typing import Tuple
