"""
Base Strategy class for trading strategies.
All strategies inherit from this abstract class.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date
from typing import Optional, List, Dict, Any, Tuple
import pandas as pd
from loguru import logger
import numpy as np

@dataclass
class StrategySignal:
    """
    Represents a trading signal generated by a strategy.
    
    INVARIANTS (enforced in __post_init__):
    - entry_price > 0
    - stop_loss < entry_price (for BUY signals)
    - target_price > entry_price (for BUY signals)
    - confidence in range [0, 10]
    - All prices are finite and positive
    """
    symbol: str
    date: date
    signal_type: str  # BUY, SELL, HOLD
    confidence: float  # 1-10 score
    entry_price: float
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    strategy_name: str = ""
    reason: str = ""  # Human-readable explanation
    indicators: Dict[str, Any] = None  # Indicator values at signal time
    
    def __post_init__(self):
        """Validate and sanitize all signal values."""
        if self.indicators is None:
            self.indicators = {}
        
        # === VALIDATE ENTRY PRICE ===
        if self.entry_price is None or self.entry_price <= 0:
            raise ValueError(f"Invalid entry_price: {self.entry_price}")
        
        self.entry_price = float(self.entry_price)
        
        # === VALIDATE/SET TARGET PRICE ===
        if self.signal_type == "BUY":
            if self.target_price is None:
                self.target_price = self.entry_price * 1.10  # Default 10%
            else:
                self.target_price = float(self.target_price)
                # INVARIANT: target must be above entry for BUY
                if self.target_price <= self.entry_price:
                    logger.debug(f"Target ({self.target_price}) <= entry, forcing +10%")
                    self.target_price = self.entry_price * 1.10
        
        # === VALIDATE/SET STOP LOSS ===
        if self.signal_type == "BUY":
            if self.stop_loss is None:
                self.stop_loss = self.entry_price * 0.95  # Default 5%
            else:
                self.stop_loss = float(self.stop_loss)
                # INVARIANT: stop must be below entry for BUY
                if self.stop_loss >= self.entry_price:
                    logger.debug(f"Stop ({self.stop_loss}) >= entry, forcing -5%")
                    self.stop_loss = self.entry_price * 0.95
                # INVARIANT: stop must be positive
                if self.stop_loss <= 0:
                    self.stop_loss = self.entry_price * 0.85  # Max 15% stop
        
        # === VALIDATE CONFIDENCE ===
        if self.confidence is None:
            self.confidence = 5.0
        else:
            self.confidence = float(self.confidence)
            # Clamp to valid range
            self.confidence = max(0.0, min(10.0, self.confidence))
        
        # === ENSURE ALL PRICES ARE ROUNDED ===
        self.entry_price = round(self.entry_price, 2)
        if self.target_price:
            self.target_price = round(self.target_price, 2)
        if self.stop_loss:
            self.stop_loss = round(self.stop_loss, 2)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Each strategy must implement:
    - name: Strategy identifier
    - analyze(): Main analysis method that returns signals
    """
    
    def __init__(self, params: Dict[str, Any] = None):
        """
        Initialize strategy with optional parameters.
        
        Args:
            params: Strategy-specific parameters for optimization
        """
        self.params = params or {}
        self._setup_params()
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Unique name for this strategy."""
        pass
    
    @property
    def description(self) -> str:
        """Human-readable description of the strategy."""
        return f"Trading strategy: {self.name}"
    
    def _setup_params(self):
        """
        Set up default parameters. Override in subclasses.
        """
        pass
    
    @abstractmethod
    def analyze(self, df: pd.DataFrame, symbol: str) -> Optional[StrategySignal]:
        """
        Analyze price data and generate signal if conditions are met.
        
        Args:
            df: DataFrame with OHLCV data and indicators
            symbol: Stock symbol
            
        Returns:
            StrategySignal if conditions met, None otherwise
        """
        pass
    
    def validate_data(self, df: pd.DataFrame, min_rows: int = 30) -> bool:
        """
        Validate that we have enough data for analysis.
        
        Args:
            df: DataFrame to validate
            min_rows: Minimum required rows
            
        Returns:
            True if valid, False otherwise
        """
        if df is None or df.empty:
            logger.warning(f"{self.name}: Empty DataFrame")
            return False
        
        if len(df) < min_rows:
            logger.warning(f"{self.name}: Insufficient data ({len(df)} < {min_rows})")
            return False
        
        return True
    
    def get_latest_values(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Get the latest row values as a dictionary.
        
        Args:
            df: DataFrame with indicators
            
        Returns:
            Dict of latest values
        """
        if df.empty:
            return {}
        return df.iloc[-1].to_dict()
    
    def calculate_confidence(self, factors: List[Tuple[str, bool, float]]) -> float:
        """
        Calculate confidence score based on multiple factors.
        
        Args:
            factors: List of (name, condition_met, weight) tuples
            
        Returns:
            Confidence score from 1-10
        """
        total_weight = sum(f[2] for f in factors)
        met_weight = sum(f[2] for f in factors if f[1])
        
        if total_weight == 0:
            return 5.0
        
        # Scale to 1-10
        raw_score = (met_weight / total_weight) * 10
        return max(1.0, min(10.0, raw_score))
    
    def _calculate_atr_based_levels(
        self, 
        df: pd.DataFrame, 
        entry: float,
        stop_multiplier: float = 2.5,
        rr_ratio: float = 1.6
    ) -> Tuple[float, float]:
        """
        Calculate ATR-based stop loss and target price.
        
        BULLETPROOF IMPLEMENTATION:
        - Validates all inputs strictly
        - Ensures stop loss is ALWAYS below entry (for long positions)
        - Ensures target is ALWAYS above entry
        - Ensures both values are positive
        - Never returns invalid prices
        
        NEPSE-OPTIMIZED: Uses 2.5x ATR for stop (accounts for 10% circuit breakers
        and higher intraday volatility compared to developed markets).
        
        Args:
            df: DataFrame with OHLC data
            entry: Entry price (MUST be positive)
            stop_multiplier: ATR multiplier for stop loss (default 2.5 for NEPSE)
            rr_ratio: Risk/Reward ratio for target calculation (default 1.6:1)
            
        Returns:
            Tuple of (stop_loss, target_price) - ALWAYS valid prices
            
        Raises:
            ValueError: If entry price is invalid (zero or negative)
        """
        # VALIDATION: Entry price must be positive
        if entry is None or entry <= 0:
            raise ValueError(f"Entry price must be positive, got: {entry}")
        
        # VALIDATION: Multipliers must be positive
        if stop_multiplier <= 0:
            logger.warning(f"Invalid stop_multiplier {stop_multiplier}, using 2.5")
            stop_multiplier = 2.5
        if rr_ratio <= 0:
            logger.warning(f"Invalid rr_ratio {rr_ratio}, using 1.6")
            rr_ratio = 1.6
        
        # Default fallback values (will be overwritten if ATR is valid)
        from core.config import settings
        default_stop_pct = getattr(settings, 'stop_loss', 0.05)  # 5% default
        default_target_pct = getattr(settings, 'target_profit', 0.10)  # 10% default
        
        stop = entry * (1 - default_stop_pct)
        target = entry * (1 + default_target_pct)
        
        try:
            # VALIDATION: DataFrame must have required columns
            if df is None or df.empty:
                logger.debug("ATR levels: DataFrame is empty, using percentage fallback")
                return self._validate_and_return_levels(entry, stop, target)
            
            required_cols = ['high', 'low', 'close']
            if not all(col in df.columns for col in required_cols):
                logger.debug("ATR levels: Missing OHLC columns, using percentage fallback")
                return self._validate_and_return_levels(entry, stop, target)
            
            # VALIDATION: Need sufficient data
            if len(df) < 15:  # 14 periods + 1
                logger.debug(f"ATR levels: Insufficient data ({len(df)} rows), using percentage fallback")
                return self._validate_and_return_levels(entry, stop, target)
            
            # Calculate ATR manually (same formula as bulletproof ATR in indicators.py)
            high = df['high'].values
            low = df['low'].values
            close = df['close'].values
            
            # Calculate True Range
            true_range = []
            for i in range(1, len(df)):
                if np.isnan(high[i]) or np.isnan(low[i]) or np.isnan(close[i-1]):
                    continue
                tr = max(
                    high[i] - low[i],
                    abs(high[i] - close[i-1]),
                    abs(low[i] - close[i-1])
                )
                true_range.append(tr)
            
            if len(true_range) < 14:
                logger.debug("ATR levels: Not enough valid TR values, using percentage fallback")
                return self._validate_and_return_levels(entry, stop, target)
            
            # ATR = Wilder's smoothed average of last 14 True Range values
            tr_series = pd.Series(true_range)
            atr = float(tr_series.ewm(alpha=1/14, min_periods=14, adjust=False).mean().iloc[-1])
            
            # VALIDATION: ATR must be positive and reasonable
            if pd.isna(atr) or atr <= 0:
                logger.debug("ATR levels: ATR is zero or NaN, using percentage fallback")
                return self._validate_and_return_levels(entry, stop, target)
            
            # VALIDATION: ATR should not exceed 20% of price (sanity check)
            if atr > entry * 0.20:
                logger.warning(f"ATR ({atr:.2f}) exceeds 20% of entry ({entry:.2f}), capping")
                atr = entry * 0.20
            
            # Calculate ATR-based stop loss
            atr_stop = entry - (stop_multiplier * atr)
            
            # VALIDATION: Stop loss must be positive and below entry
            # Minimum stop: 1% below entry (to ensure meaningful stop)
            # Maximum stop: 15% below entry (to prevent excessive loss)
            min_stop = entry * 0.85  # Max 15% loss
            max_stop = entry * 0.99  # Min 1% loss
            
            if atr_stop < min_stop:
                logger.debug(f"ATR stop ({atr_stop:.2f}) too far, capping at 15% ({min_stop:.2f})")
                atr_stop = min_stop
            elif atr_stop > max_stop:
                logger.debug(f"ATR stop ({atr_stop:.2f}) too close, setting to 1% ({max_stop:.2f})")
                atr_stop = max_stop
            
            stop = atr_stop
            
            # Calculate target based on R:R ratio
            risk = entry - stop
            target = entry + (rr_ratio * risk)
            
            logger.debug(
                f"ATR-based levels: ATR={atr:.2f}, "
                f"Stop={stop:.2f} ({stop_multiplier}x ATR), "
                f"Target={target:.2f} (R:R={rr_ratio:.1f})"
            )
            
        except Exception as e:
            logger.debug(f"ATR calculation failed: {e}, using percentage fallback")
        
        return self._validate_and_return_levels(entry, stop, target)
    
    def _validate_and_return_levels(
        self, 
        entry: float, 
        stop: float, 
        target: float
    ) -> Tuple[float, float]:
        """
        Final validation to ensure stop/target are mathematically valid.
        
        INVARIANTS (for long positions):
        1. stop < entry (stop loss below entry)
        2. target > entry (target above entry)
        3. All values > 0 (positive prices)
        4. All values are finite (no inf/nan)
        """
        # Fix NaN/inf
        if pd.isna(stop) or np.isinf(stop):
            stop = entry * 0.95
        if pd.isna(target) or np.isinf(target):
            target = entry * 1.10
        
        # Ensure positive
        stop = max(1.0, stop)  # Minimum Rs. 1
        target = max(1.0, target)
        
        # INVARIANT: stop must be below entry
        if stop >= entry:
            stop = entry * 0.95  # Force 5% below
            logger.warning(f"Stop >= entry, forcing to {stop:.2f}")
        
        # INVARIANT: target must be above entry
        if target <= entry:
            target = entry * 1.10  # Force 10% above
            logger.warning(f"Target <= entry, forcing to {target:.2f}")
        
        # Round to 2 decimal places
        return round(stop, 2), round(target, 2)


# Type alias for strategy signal with type hint
from typing import Tuple
